Update post.js
DFE-Digital/login.dfe.profile pull request #240
Opened 2022-10-19 15:46 UTC by malikimran34

2022-10-19 16:23 UTC, ipredoi reviewed
please update the unit tests in `test/unit/app/changePassword/post.spec.js:185:43`

2022-10-19 16:23 UTC, Avinash-teky approved these changes

2022-10-19 16:24 UTC, ipredoi requested changes
please update the unit tests in `test/unit/app/changePassword/post.spec.js`

2022-10-20 10:54 UTC, ipredoi approved these changes
👍

2022-10-25 08:54 UTC, merged