Redirection error fix(NSA-6607)
DFE-Digital/login.dfe.profile pull request #251
Opened 2023-01-25 13:37 UTC by rashthedude

2023-01-25 14:38 UTC, ipredoi commented on src/app/register/views/verify.ejs
> +<% } else if (locals.email && !locals.showResendLink && !locals.duplicateEntry) { %>
Can we replace `else if` statement with `else` statement - by using `else if` the page will lose the form to insert the verify code and will display only the green and the blue banner

2023-01-25 14:40 UTC, ipredoi commented on src/app/register/views/verify.ejs
> +<% } else { %>
Can we remove the `else` statement to display the verification code form when the email is valid?

2023-01-25 14:45 UTC, ipredoi requested changes
Can we please change the else and else if statements to bring back the Confirm email address form?
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/70764046/214592998-c0100781-1123-4b58-b9c6-3a8cf71a796f.png">

Can you please check if npm  version is `6.14.15` when installing packages?

2023-01-25 14:58 UTC, malikimran34 approved these changes

2023-01-25 15:39 UTC, rashthedude commented on src/app/register/views/verify.ejs
> +<% } else { %>
See above comment.

2023-01-26 12:04 UTC, rashthedude commented on src/app/register/views/verify.ejs
> +<% } else if (locals.email && !locals.showResendLink && !locals.duplicateEntry) { %>
Logic further simplified. Can you have a look at it again please @ipredoi ?

2023-01-26 15:13 UTC, ipredoi approved these changes
👍

2023-01-26 15:14 UTC, ipredoi commented on src/app/register/views/verify.ejs
> +<% } else if (locals.email && !locals.showResendLink && !locals.duplicateEntry) { %>
Looks good now. Thanks Rashid

2023-01-27 13:43 UTC, merged